"use client";
import Tiptap from "@/components/text-editor";
import React, { useState } from "react";
import Chart from "./chart";
import { BookOpenCheck, SearchCode } from "lucide-react";

export default function Page() {
  const [selectedOptions, setSelectedOptions] = useState<string[]>([]);
  const [editorContent, setEditorContent] = useState("");
  const [percentage, setPercentage] = useState(0);
  const [isChecking, setIsChecking] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const options = [
    {
      name: "AI detector",
      value: "ai-detector",
      icon: <SearchCode />,
      cost: "1 credit per word",
      prompt:
        "Detect if the text is generated by AI or human. return a percentage of how likely the text is generated by AI.",
    },
    {
      name: "Plagiarism",
      value: "plagiarism",
      icon: <BookOpenCheck />,
      cost: "2 credit per word",
      prompt:
        "Detect if the text is plagiarized. return a percentage of how likely the text is plagiarized.",
    },
    {
      name: "Fact checker",
      value: "fact-checker",
      icon: <BookOpenCheck />,
      cost: "1 credit per word",
      prompt:
        "Detect if the text contains false information. return a percentage of how likely the text is false.",
    },
    {
      name: "Feedback",
      value: "writing-feedback",
      icon: <BookOpenCheck />,
      cost: "1 credit per word",
      prompt:
        "Provide feedback on the writing quality of the text. return a percentage of the writing quality of the text.",
    },
    // {
    //   name: "Grammar checker",
    //   value: "grammar-checker",
    //   icon: <SpellCheck />,
    //   cost: "2 credit per word",
    //   prompt: "Check the grammar of the text. return the corrected text.",
    // },
    // {
    //   name: "Summarizer",
    //   value: "summarizer",
    //   icon: <FileSearch />,
    //   cost: "1 credit per word",
    //   prompt: "Summarize the text. return a summary of the text.",
    // },
  ];

  const selectedOptionNames = options
    .filter((option) => selectedOptions.includes(option.value))
    .map((option) => option.name)
    .join(", ");

  const toggleOption = (value: string) => {
    setSelectedOptions((prev) =>
      prev.includes(value)
        ? prev.filter((item) => item !== value)
        : [...prev, value],
    );
  };

  const extractTextFromHtml = (html: string) => {
    if (!html.trim()) return "";
    const doc = new DOMParser().parseFromString(html, "text/html");
    return (doc.body.textContent || "").trim();
  };

  const parsePercentage = (text: string) => {
    const match = text.match(/(\d+(?:\.\d+)?)\s*%?/);
    if (!match) return null;

    const numericValue = Number(match[1]);
    if (Number.isNaN(numericValue)) return null;

    return Math.max(0, Math.min(100, Math.round(numericValue)));
  };

  const readStreamedText = async (response: Response) => {
    if (!response.body) return "";

    const reader = response.body.getReader();
    const decoder = new TextDecoder();
    let done = false;
    let accumulated = "";

    while (!done) {
      const result = await reader.read();
      done = result.done ?? false;
      if (result.value) {
        accumulated += decoder.decode(result.value, { stream: !done });
      }
    }

    return accumulated.trim();
  };

  const handleCheck = async () => {
    setError(null);

    if (!selectedOptions.length) {
      setError("Select at least one option.");
      return;
    }

    const plainText = extractTextFromHtml(editorContent);
    if (!plainText) {
      setError("Enter text before running the check.");
      return;
    }

    //     const selectedPrompts = options
    //       .filter((option) => selectedOptions.includes(option.value))
    //       .map((option) => `- ${option.name}: ${option.prompt}`)
    //       .join("\n");

    //     const prompt = `Analyze the user text using ONLY these checks:
    // ${selectedPrompts}

    // Return only one numeric percentage from 0 to 100 (no explanation, no extra words).

    // User text:
    // ${plainText}`;

    const selectedPrompt = options.find((opt) =>
      selectedOptions.includes(opt.value),
    );

    const prompt = `
${selectedPrompt?.prompt}

Return ONLY a number between 0 and 100.
Do not explain.

Text:
${plainText}
`;

    try {
      setIsChecking(true);
      const response = await fetch("/api/gemini/stream", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt }),
      });

      if (!response.ok) {
        throw new Error("Failed to get response from Gemini.");
      }

      const output = await readStreamedText(response);
      console.log("gene output", output);
      const parsed = parsePercentage(output);

      if (parsed === null) {
        setError("Could not read a percentage from Gemini response.");
        return;
      }

      setPercentage(parsed);
    } catch (requestError) {
      console.error(requestError);
      setError("Failed to run check. Please try again.");
    } finally {
      setIsChecking(false);
    }
  };

  return (
    <div className="flex flex-col lg:flex-row min-h-screen">
      <div className="flex flex-col flex-grow lg:w-3/5 text-center md:text-start border-r border-gray-200 pt-6 md:px-6 bg-[#0F2854]">
        <h2 className="text-2xl font-bold text-gray-300">Plagiarism Checker</h2>
        <p className="text-sm text-gray-300 mb-4">
          Check your text for plagiarism
        </p>
        <div className="flex-grow flex flex-col">
          <Tiptap onChange={setEditorContent} />
        </div>
      </div>
      <div className="flex flex-col flex-grow lg:w-2/5 border p-6 bg-[#0F2854]">
        <div className="grid grid-cols-2 gap-4 ">
          {options.map((option) => (
            <div
              key={option.value}
              className={`border flex gap-4 p-4 rounded-lg transition-colors ${
                selectedOptions.includes(option.value)
                  ? "border-(--brand-primary) bg-(--brand-primary) text-gray-300"
                  : "border-gray-300 bg-transparent text-gray-300"
              }`}
            >
              <div className="flex items-center gap-2 mb-2">{option.icon}</div>
              <div className="mr-10">
                <h3 className="text-lg font-semibold">{option.name}</h3>
                <p className="text-sm text-gray-300">{option.cost}</p>
              </div>
              <input
                type="checkbox"
                checked={selectedOptions.includes(option.value)}
                onChange={() => toggleOption(option.value)}
                className="w-5 accent-(--brand-primary)"
              />
            </div>
          ))}
        </div>
        <div className="flex flex-col gap-2">
          <button
            onClick={handleCheck}
            disabled={isChecking}
            className="bg-[#1C4D8D] text-gray-300 text-2xl mt-6 p-2 rounded-lg disabled:opacity-60"
          >
            {isChecking ? "Checking..." : "Check"}
          </button>
          {selectedOptionNames ? (
            <p className="text-xs text-gray-300">
              Selected: {selectedOptionNames}
            </p>
          ) : null}
          {error ? <p className="text-sm text-red-600">{error}</p> : null}
        </div>
        <Chart percentage={percentage} />
      </div>
    </div>
  );
}